// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestePraticoQualyTeam.Data;

namespace TestePraticoQualyTeam.Migrations
{
    [DbContext(typeof(TestePraticoQualyTeamContext))]
    partial class TestePraticoQualyTeamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("TestePraticoQualyTeam.Model.Documento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("arquivo")
                        .HasColumnType("longblob");

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("codigo")
                        .HasColumnType("int");

                    b.Property<string>("nomeArquivo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("processoID")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.HasIndex("codigo")
                        .IsUnique();

                    b.HasIndex("processoID");

                    b.ToTable("Documento");
                });

            modelBuilder.Entity("TestePraticoQualyTeam.Model.Processo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Processo");
                });

            modelBuilder.Entity("TestePraticoQualyTeam.Model.Documento", b =>
                {
                    b.HasOne("TestePraticoQualyTeam.Model.Processo", "processo")
                        .WithMany()
                        .HasForeignKey("processoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("processo");
                });
#pragma warning restore 612, 618
        }
    }
}
